// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkuZ2r56PW8WuehahlrDlqH5ljyZaZqX0',
    appId: '1:332556988087:web:d4f373a6339d22ce09e732',
    messagingSenderId: '332556988087',
    projectId: 'my-todo-app-95b85',
    authDomain: 'my-todo-app-95b85.firebaseapp.com',
    storageBucket: 'my-todo-app-95b85.firebasestorage.app',
    measurementId: 'G-LT4S1V7MYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpGFydn6ZtJa_g-VjWUF9bWm-TAiLyz40',
    appId: '1:332556988087:android:aa2f28369788f5ec09e732',
    messagingSenderId: '332556988087',
    projectId: 'my-todo-app-95b85',
    storageBucket: 'my-todo-app-95b85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP4LAioaetmXvzckXWsW6iiuaD4gSNk8U',
    appId: '1:332556988087:ios:935306cbbbdddbe709e732',
    messagingSenderId: '332556988087',
    projectId: 'my-todo-app-95b85',
    storageBucket: 'my-todo-app-95b85.firebasestorage.app',
    iosBundleId: 'com.example.myTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP4LAioaetmXvzckXWsW6iiuaD4gSNk8U',
    appId: '1:332556988087:ios:935306cbbbdddbe709e732',
    messagingSenderId: '332556988087',
    projectId: 'my-todo-app-95b85',
    storageBucket: 'my-todo-app-95b85.firebasestorage.app',
    iosBundleId: 'com.example.myTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkuZ2r56PW8WuehahlrDlqH5ljyZaZqX0',
    appId: '1:332556988087:web:60b2565f6c5c725c09e732',
    messagingSenderId: '332556988087',
    projectId: 'my-todo-app-95b85',
    authDomain: 'my-todo-app-95b85.firebaseapp.com',
    storageBucket: 'my-todo-app-95b85.firebasestorage.app',
    measurementId: 'G-5GEB58WVMQ',
  );
}
